version: '3.8'

services:
  laravel.test:
    image: laravelsail/php80-composer
    ports:
      - '80:80'
    environment:
      - APP_PORT=80
      - WWWUSER=1000
      - WWWGROUP=1000
    volumes:
      - ./:/var/www/html
    networks:
      - sail

  mysql:
    image: 'mysql:5.7'
    ports:
      - '3310:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=streamteam
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Root8888!
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sail

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  mysql_data: